language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - gitbook build . ./build
  - touch ./build/.nojekyll

before_deploy:
      - git config --local user.name "robot"
      - git config --local user.email "robot@localhost"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    fqdn: "ziwolianghua.com"
    on:
      branch: master
