name: build-book
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/book.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: setup env to build website
        run: |
          npm install honkit -g
          gitbook install
      - name: setup env to generate file
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export TZ='Asia/Shanghai'
          sudo apt-get install calibre fonts-noto-cjk -y
         
      - name: build website
        run: |
          honkit build . ./build
          rm -rf ./build/.github
          echo "" > ./build/.nojekyll
      - name: generate file
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir book
          xvfb-run gitbook pdf ./ ./book/book.pdf
          honkit epub ./ ./book/book.epub
          honkit mobi ./ ./book/book.mobi
      - name: upload to qcloud
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.TENCENT_CLOUD_BUCKET }}
          cos_region: ap-guangzhou
          local_path: book
          remote_path: /
          clean: true
